packages:
    - 'packages/@lwc/aria-reflection'
    - 'packages/@lwc/errors'
    - 'packages/@lwc/shared'
    - 'packages/@lwc/signals'
    - 'packages/@lwc/features'
    - 'packages/@lwc/synthetic-shadow'
    - 'packages/@lwc/engine-core'
    - 'packages/@lwc/engine-dom'
    - 'packages/@lwc/wire-service'
    - 'packages/@lwc/module-resolver'
    - 'packages/@lwc/ssr-runtime'
    - 'packages/@lwc/template-compiler'
    - 'packages/@lwc/style-compiler'
    - 'packages/@lwc/ssr-compiler'
    - 'packages/@lwc/babel-plugin-component'
    - 'packages/@lwc/compiler'
    - 'packages/@lwc/rollup-plugin'
    - 'packages/@lwc/engine-server'
    - 'packages/lwc'
    - 'playground'
