import { LWC_VERSION } from '@lwc/shared';
import {
    API_VERSION,
    DISABLE_STATIC_CONTENT_OPTIMIZATION,
    DISABLE_SYNTHETIC,
    ENABLE_ARIA_REFLECTION_GLOBAL_POLYFILL,
    ENABLE_SYNTHETIC_SHADOW_IN_HYDRATION,
    FORCE_NATIVE_SHADOW_MODE_FOR_TEST,
    NODE_ENV_FOR_TEST,
} from './browser/shared/options';
// import type { ViteUserConfig } from 'vitest/config';

export default {
    API_VERSION: API_VERSION,
    DISABLE_STATIC_CONTENT_OPTIMIZATION: DISABLE_STATIC_CONTENT_OPTIMIZATION,
    ENABLE_ARIA_REFLECTION_GLOBAL_POLYFILL: ENABLE_ARIA_REFLECTION_GLOBAL_POLYFILL,
    ENABLE_SYNTHETIC_SHADOW_IN_HYDRATION: ENABLE_SYNTHETIC_SHADOW_IN_HYDRATION,
    FORCE_NATIVE_SHADOW_MODE_FOR_TEST: FORCE_NATIVE_SHADOW_MODE_FOR_TEST,
    LWC_VERSION: LWC_VERSION,
    NATIVE_SHADOW: DISABLE_SYNTHETIC || FORCE_NATIVE_SHADOW_MODE_FOR_TEST,
    NODE_ENV: NODE_ENV_FOR_TEST || 'development',
} as any;
